-- Glowva SaaS baseline schema, RLS, analytics views, usage limits, and payment-safe subscriptions.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  plan text not null default 'free',
  is_subscribed boolean not null default false,
  subscription_status text not null default 'inactive',
  subscription_provider text,
  subscription_customer_id text,
  subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_plan_check check (plan in ('free', 'monthly', 'yearly', 'enterprise')),
  constraint profiles_subscription_status_check check (subscription_status in ('inactive', 'trialing', 'active', 'past_due', 'canceled'))
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  country text,
  city text,
  path text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.searches (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  product_name text,
  query text,
  country text,
  city text,
  result jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_type text not null,
  actor_id text not null,
  ip text,
  created_at timestamptz not null default now(),
  constraint usage_events_actor_type_check check (actor_type in ('ip', 'user', 'email'))
);

create index if not exists usage_events_actor_window_idx
  on public.usage_events (event_type, actor_type, actor_id, created_at desc);

create table if not exists public.usage_counters (
  event_type text not null,
  actor_type text not null,
  actor_id text not null,
  window_start timestamptz not null,
  count int not null default 0,
  updated_at timestamptz not null default now(),
  primary key (event_type, actor_type, actor_id, window_start),
  constraint usage_counters_actor_type_check check (actor_type in ('ip', 'user', 'email'))
);

create table if not exists public.analysis_cache (
  cache_key text primary key,
  result jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists analysis_cache_expires_at_idx on public.analysis_cache (expires_at);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  event_type text not null,
  payload jsonb not null,
  processed_at timestamptz not null default now(),
  unique (provider, event_id)
);

alter table public.profiles enable row level security;
alter table public.visits enable row level security;
alter table public.searches enable row level security;
alter table public.usage_events enable row level security;
alter table public.usage_counters enable row level security;
alter table public.analysis_cache enable row level security;
alter table public.payment_events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select to authenticated
  using (id = auth.uid());

drop policy if exists "profiles_insert_own_safe" on public.profiles;
create policy "profiles_insert_own_safe" on public.profiles
  for insert to authenticated
  with check (
    id = auth.uid()
    and coalesce(is_subscribed, false) = false
    and coalesce(plan, 'free') = 'free'
    and coalesce(subscription_status, 'inactive') = 'inactive'
    and subscription_provider is null
    and subscription_customer_id is null
    and subscription_id is null
  );

drop policy if exists "profiles_update_own_non_subscription" on public.profiles;
create policy "profiles_update_own_non_subscription" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and is_subscribed = false
    and plan = 'free'
    and subscription_status = 'inactive'
    and subscription_provider is null
    and subscription_customer_id is null
    and subscription_id is null
  );

drop policy if exists "visits_no_client_access" on public.visits;
create policy "visits_no_client_access" on public.visits
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "searches_select_own" on public.searches;
create policy "searches_select_own" on public.searches
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "searches_no_client_write" on public.searches;
create policy "searches_no_client_write" on public.searches
  for insert to anon, authenticated
  with check (false);

drop policy if exists "usage_events_no_client_access" on public.usage_events;
create policy "usage_events_no_client_access" on public.usage_events
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "usage_counters_no_client_access" on public.usage_counters;
create policy "usage_counters_no_client_access" on public.usage_counters
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "analysis_cache_no_client_access" on public.analysis_cache;
create policy "analysis_cache_no_client_access" on public.analysis_cache
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "payment_events_no_client_access" on public.payment_events;
create policy "payment_events_no_client_access" on public.payment_events
  for all to anon, authenticated
  using (false)
  with check (false);

create or replace function public.enforce_usage_limit(
  p_event_type text,
  p_actor_type text,
  p_actor_id text,
  p_ip text,
  p_window_start timestamptz,
  p_limit int
)
returns table (allowed boolean, remaining int)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_count int;
begin
  if p_limit < 1 then
    return query select false, 0;
    return;
  end if;

  insert into public.usage_counters (event_type, actor_type, actor_id, window_start, count)
  values (p_event_type, p_actor_type, p_actor_id, p_window_start, 1)
  on conflict (event_type, actor_type, actor_id, window_start)
  do update
    set count = public.usage_counters.count + 1,
        updated_at = now()
  returning count into current_count;

  if current_count > p_limit then
    return query select false, 0;
    return;
  end if;

  insert into public.usage_events (event_type, actor_type, actor_id, ip)
  values (p_event_type, p_actor_type, p_actor_id, p_ip);

  return query select true, greatest(p_limit - current_count, 0);
end;
$$;

revoke all on function public.enforce_usage_limit(text, text, text, text, timestamptz, int) from public;
revoke all on function public.enforce_usage_limit(text, text, text, text, timestamptz, int) from anon;
revoke all on function public.enforce_usage_limit(text, text, text, text, timestamptz, int) from authenticated;
grant execute on function public.enforce_usage_limit(text, text, text, text, timestamptz, int) to service_role;

create or replace view public.v_top_products
with (security_invoker = true)
as
select product_name, count(*)::int as search_count
from public.searches
where product_name is not null
group by product_name
order by search_count desc
limit 20;

create or replace view public.v_by_country
with (security_invoker = true)
as
select coalesce(country, 'unknown') as country, count(*)::int as count
from public.visits
group by coalesce(country, 'unknown')
order by count desc;

create or replace view public.v_by_city
with (security_invoker = true)
as
select coalesce(city, 'unknown') as city, count(*)::int as count
from public.visits
group by coalesce(city, 'unknown')
order by count desc;

create or replace view public.v_daily_searches
with (security_invoker = true)
as
select date_trunc('day', created_at)::date as day, count(*)::int as search_count
from public.searches
group by date_trunc('day', created_at)::date
order by day asc;

create or replace view public.v_funnel
with (security_invoker = true)
as
select 'زيارات' as label, count(*)::int as count from public.visits
union all
select 'بحث' as label, count(*)::int as count from public.searches
union all
select 'مشتركين' as label, count(*)::int as count
from public.profiles
where is_subscribed = true;

revoke all on public.v_top_products from anon, authenticated;
revoke all on public.v_by_country from anon, authenticated;
revoke all on public.v_by_city from anon, authenticated;
revoke all on public.v_daily_searches from anon, authenticated;
revoke all on public.v_funnel from anon, authenticated;
